#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform image2D outputImage;

void main()
{	
	 
	vec4 color     = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y));
	float contrast = 4;
    color = vec4(((color.rgb - vec3(0.5)) * contrast + vec3(0.5)), color.w);

	imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), color);
}