#version 450

layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform image2D outputImage;

void main()
{
	vec4 color = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y));
	color = vec4(pow(color.rgb, vec3(2.2, 2.5, 2.7)), color.w);
	imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), color);
}
